### POST request to blog
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title": "제목",
  "content": "내용"
}

### GET 블로그 전체 조회
GET http://localhost:8080/api/articles

### GET 블로그 단건 조회
GET http://localhost:8080/api/articles/5